#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_DIR="${OUT_DIR:-$ROOT_DIR/dist/arch}"
WORK_DIR="${WORK_DIR:-$(mktemp -d)}"
KEEP_WORKDIR="${KEEP_WORKDIR:-0}"
LOW_MEMORY_BUILD="${LOW_MEMORY_BUILD:-1}"
GPG_KEY="${GPG_KEY:-B2B8E2F00629B64ADEEBC5AF7903F448BD7BBBF1}"
SIGN_PACKAGES="${SIGN_PACKAGES:-1}"
PUBLIC_KEY_NAME="libertypo-release-key.asc"

if [[ "${1:-}" == "--script-help" ]]; then
  cat <<'EOF'
Build an Arch package for this Proton VPN GTK app checkout.

Usage:
  ./build-arch-proton-vpn-package.sh [makepkg options]

Examples:
  ./build-arch-proton-vpn-package.sh -f
  ./build-arch-proton-vpn-package.sh -f --syncdeps --cleanbuild

Environment variables:
  OUT_DIR       Output directory for built package (default: dist/arch)
  WORK_DIR      Temporary working directory (default: mktemp dir)
  KEEP_WORKDIR  Set to 1 to keep WORK_DIR after script exits
  LOW_MEMORY_BUILD  Set to 1 (default) for low-memory makepkg/compression settings
  GPG_KEY       Signing-key fingerprint (default: libertypo release key)
  SIGN_PACKAGES Set to 0 to skip GPG signatures for developer builds

Notes:
  This script is build-only and will never install the package.
  Passing -i or --install is rejected.
  Build dependencies are not auto-installed by this script.
  Runtime dependencies are declared in the built package and installed by pacman.
  The package emits install-time warnings if nm-protun artifacts are missing.
EOF
  exit 0
fi

for arg in "$@"; do
  if [[ "$arg" == "-i" || "$arg" == "--install" ]]; then
    echo "error: install options (-i/--install) are not allowed; this script only builds packages." >&2
    exit 1
  fi
done

required_files=(
  "$ROOT_DIR/run-app.sh"
  "$ROOT_DIR/versions.yml"
  "$ROOT_DIR/proton"
  "$ROOT_DIR/python-proton-vpn-api-core"
)

for f in "${required_files[@]}"; do
  if [[ ! -e "$f" ]]; then
    echo "error: required path missing: $f" >&2
    exit 1
  fi
done

if ! command -v makepkg >/dev/null 2>&1; then
  echo "error: makepkg is required (install pacman-contrib/base-devel)." >&2
  exit 1
fi

if [[ "$SIGN_PACKAGES" == "1" ]] && ! command -v gpg >/dev/null 2>&1; then
  echo "error: gpg is required to sign package artifacts." >&2
  exit 1
fi

if [[ "$SIGN_PACKAGES" == "1" ]] && ! gpg --batch --list-secret-keys "$GPG_KEY" >/dev/null 2>&1; then
  echo "error: configured signing key is not available: $GPG_KEY" >&2
  exit 1
fi

if [[ "$KEEP_WORKDIR" != "1" ]]; then
  trap 'rm -rf "$WORK_DIR"' EXIT
fi

mkdir -p "$OUT_DIR"
gpg --batch --export-options export-minimal --armor --export "$GPG_KEY" > "$OUT_DIR/$PUBLIC_KEY_NAME"
cp "$ROOT_DIR/install-arch-testing-packages.sh" "$OUT_DIR/install-arch-testing-packages.sh"
chmod 755 "$OUT_DIR/install-arch-testing-packages.sh"
PACKAGE_NAME="proton-vpn-gtk-app-community"
PKGDIR="$WORK_DIR/$PACKAGE_NAME"
mkdir -p "$PKGDIR"

APP_VERSION="$(awk '/^version:/ {print $2; exit}' "$ROOT_DIR/versions.yml")"
if [[ -z "$APP_VERSION" ]]; then
  echo "error: could not read version from versions.yml" >&2
  exit 1
fi
PKGVER="${COMMUNITY_VERSION:-1.0}"

TARBALL_NAME="${PACKAGE_NAME}-${PKGVER}.tar.gz"
SOURCE_DIR="${PACKAGE_NAME}-${PKGVER}"

# Only include runtime-relevant files to avoid huge archive/build memory use.
archive_paths=(
  run-app.sh
  versions.yml
  proton
  python-proton-vpn-api-core
)

for p in "${archive_paths[@]}"; do
  if [[ ! -e "$ROOT_DIR/$p" ]]; then
    echo "error: required archive path missing: $ROOT_DIR/$p" >&2
    exit 1
  fi
done

optional_archive_paths=(LICENSE README README.md)
for p in "${optional_archive_paths[@]}"; do
  if [[ -e "$ROOT_DIR/$p" ]]; then
    archive_paths+=("$p")
  fi
done

GZIP=-n tar \
  --exclude-vcs \
  --exclude='__pycache__' \
  --exclude='*.pyc' \
  --exclude='python-proton-vpn-api-core' \
  --exclude='proton/vpn/backend' \
  --exclude='proton/vpn/connection' \
  --exclude='proton/vpn/core' \
  --exclude='proton/vpn/killswitch' \
  --exclude='proton/vpn/logging' \
  --exclude='proton/vpn/session' \
  --exclude='proton/vpn/split_tunneling' \
  --exclude='proton/vpn/__init__.py' \
  --sort=name \
  --mtime='UTC 1970-01-01' \
  --owner=0 \
  --group=0 \
  --numeric-owner \
  --transform "s|^|${SOURCE_DIR}/|" \
  -czf "$PKGDIR/$TARBALL_NAME" \
  -C "$ROOT_DIR" \
  "${archive_paths[@]}"

cat > "$PKGDIR/README.txt" <<'TXT'
This directory is generated by build-arch-proton-vpn-package.sh.
Run makepkg here to build an installable package for the Proton VPN GTK app.
TXT

PACKAGING_DIR="$ROOT_DIR/packaging/arch/proton-vpn-gtk-app-unofficial"
cp "$PACKAGING_DIR/PKGBUILD" "$PKGDIR/PKGBUILD"
cp "$PACKAGING_DIR/proton-vpn-gtk-app-unofficial.install" "$PKGDIR/$PACKAGE_NAME.install"
cp "$PACKAGING_DIR/proton-vpn-gtk-app-unofficial.desktop" "$PKGDIR/$PACKAGE_NAME.desktop"
sed -i "s/^pkgver=.*/pkgver=${PKGVER}/" "$PKGDIR/PKGBUILD"
SOURCE_ARCHIVE_SHA256="$(sha256sum "$PKGDIR/$TARBALL_NAME" | awk '{print $1}')"
DESKTOP_SHA256="$(sha256sum "$PKGDIR/$PACKAGE_NAME.desktop" | awk '{print $1}')"
sed -i \
  -e "s/SOURCE_ARCHIVE_SHA256/${SOURCE_ARCHIVE_SHA256}/" \
  -e "s/DESKTOP_SHA256/${DESKTOP_SHA256}/" \
  "$PKGDIR/PKGBUILD"

echo "==> Building Arch package in: $PKGDIR"
(
  cd "$PKGDIR"
  if [[ "$LOW_MEMORY_BUILD" == "1" ]]; then
    echo "==> Low-memory mode enabled (MAKEFLAGS=-j1, zstd -T1 -3)."
    cat > makepkg.lowmem.conf <<'EOF'
  source /etc/makepkg.conf
MAKEFLAGS="-j1"
COMPRESSZST=(zstd -c -T1 -3 -)
PKGEXT='.pkg.tar.zst'
EOF
    MAKEFLAGS="-j1" makepkg --config "$PKGDIR/makepkg.lowmem.conf" -f "$@"
  else
    makepkg -f "$@"
  fi
)

packages=()
for artifact in "$PKGDIR"/*.pkg.tar.*; do
  [[ -f "$artifact" && "$artifact" =~ \.pkg\.tar\.[^.]+$ ]] || continue
  packages+=("$artifact")
done

if [[ ${#packages[@]} -eq 0 ]]; then
  echo "==> No package archive produced (makepkg option may have skipped build)."
  echo "==> Working directory: $PKGDIR"
  exit 0
fi

# Remove older non-bin artifacts from output to avoid accidental install of legacy package names.
legacy_patterns=(
  "$OUT_DIR/proton-vpn-gtk-app-community*.pkg.tar.*"
  "$OUT_DIR/proton-vpn-gtk-app-unofficial*.pkg.tar.*"
)
shopt -s nullglob
legacy_packages=()
for legacy_pattern in "${legacy_patterns[@]}"; do
  mapfile -t matched_packages < <(compgen -G "$legacy_pattern" || true)
  legacy_packages+=("${matched_packages[@]}")
done
shopt -u nullglob
if [[ ${#legacy_packages[@]} -gt 0 ]]; then
  rm -f "${legacy_packages[@]}"
fi

cp -f "${packages[@]}" "$OUT_DIR"/

for package in "${packages[@]}"; do
  package_name="$(basename "$package")"
  (
    cd "$OUT_DIR"
    sha256sum "$package_name" > "$package_name.sha256"
    if [[ "$SIGN_PACKAGES" == "1" ]]; then
      gpg --batch --yes --local-user "$GPG_KEY" --detach-sign --output "$package_name.sig" "$package_name"
    else
      rm -f "$package_name.sig"
    fi
  )
done

echo "==> Package copied to: $OUT_DIR"
ls -1 "$OUT_DIR"/*.pkg.tar.*
echo "==> SHA-256 checksums: $OUT_DIR/*.pkg.tar.*.sha256"
echo "==> Public signing key: $OUT_DIR/$PUBLIC_KEY_NAME"
if [[ "$SIGN_PACKAGES" == "1" ]]; then
  echo "==> GPG signatures: $OUT_DIR/*.pkg.tar.*.sig"
fi

app_packages=()
for artifact in "$OUT_DIR"/proton-vpn-gtk-app-community-*.pkg.tar.*; do
  [[ -f "$artifact" && "$artifact" =~ \.pkg\.tar\.[^.]+$ ]] || continue
  app_packages+=("$artifact")
done
if [[ ${#app_packages[@]} -gt 0 ]]; then
  latest_package="${app_packages[-1]}"
  echo "==> Install with: sudo pacman -U '$latest_package'"
fi
